image: docker:stable
services:
  - docker:dind
stages:
  - Build image

docker build:
  stage: Build image
  script:
  - docker info
  - docker login registry.gitlab.com
  - docker build -t registry.gitlab.com/barathbk/loadtest-client .
  - docker push registry.gitlab.com/barathbk/loadtest-client