image: docker:stable
services:
  - docker:dind
stages:
  - Build image
  - Push to Docker Hub
before_script:
  - docker login -u "$USER_NAME" -p "$PASSWORD" $REGISTRY

docker build:
  stage: Build image
  script:
  - docker info
  - docker build -t loadtest-client .
  - docker image ls

docker push:
  stage: Push to Docker Hub
  only:
  - master
  script:
  - docker login -u "$USER_NAME" -p "$PASSWORD"
  - docker push barathBK/loadtest-client
